### PR TITLE
Update java-se.adoc with current supported level of Java 18

### PR DESCRIPTION
**Pull request by jgrassel**
Signed-off-by: Joe Grassel <jgrassel@us.ibm.com>

### CODE REVIEW

**Comment by dmuelle** [comment]
we have other changes in this file that have not gone to production yet (but will with 22.0.0.3). Merging these changes will result in branch conflicts. As an alternative, we can create the update as part of #5232 and send the PR for your review

**Comment by jgrassel** [comment]
That sounds good to me.

**Comment by dmuelle** [comment]
actually I just realized these changes have in fact gone to prod. Retargeting this for draft and we will move it to staging and vNext from there.

**Comment by jgrassel** [comment]
BTW, Java 18 support is for 22.0.0.4, not for 22.0.0.3, so make sure that doesn't get into the 20.0.0.3 doc.

**Pull request merged**
