### PR TITLE
Update security-vulnerabilities.adoc

### PR DESCRIPTION
**Pull request by bfanning**
CVE update for 20.0.0.1

### CODE REVIEW

**Comment by cbridgha** [comment]
Don't merge this until 1/17 AM!!

**Comment by bfanning** [comment]
@Charlotte-Holt @cbridgha    Since we "shouldn't" use .x then we should list out all  mpOpenapi-1.0, mpOpenapi-1.1  and openapi-3.0, openapi-3.1

**Comment by Charlotte-Holt** [comment]
@bfanning Yes, that's good. Thanks!

**Comment by Charlotte-Holt** [comment]
@bfanning Could you update this so we can merge it this AM?

**Comment by cbridgha** [comment]
I made the changes on my branch - https://github.com/OpenLiberty/docs/pull/933

I'll close this out.

**Pull request closed without merging**
