### PR TITLE
Dm rest clients final

### PR DESCRIPTION
**Pull request by dmuelle**

### CODE REVIEW

**Comment by steven1046** [comment]
Hi @lauracowen, there were a few images on the site over 100% width so i'm looking to fix those before delivering the image width cap.

**Comment by lauracowen** [comment]
> Hi @lauracowen, there were a few images on the site over 100% width so i'm looking to fix those before delivering the image width cap.

@steven1046 Could you merge this PR when you merge yours, pls? (in case I'm not here)

Then @dmuelle can you check it all looks okay, then paste a link in the issue and close it etc?

**Comment by steven1046** [comment]
The image UI changes are in master, so https://openlibertydev.mybluemix.net will have the correct pages once it's rebuilt.

**Comment by steven1046** [comment]
https://openlibertydev.mybluemix.net/docs/ref/general/#rest_clients.html

**Pull request merged**
