### PR TITLE
Issue #3782: Add %D and %{R}W to NCSA Logging Examples

### PR DESCRIPTION
**Pull request by kgibm**
See Issue #3782 

https://docs-draft-openlibertyio.mybluemix.net/docs/21.0.0.3/access-logging.html

### CODE REVIEW

**Review by dmuelle — APPROVED** [review]
LGTM- I can merge it in unless you'd like anyone else to review as well

**Comment by kgibm** [comment]
@dmuelle Reviews are complete so you may merge. Thanks!

**Comment by dmuelle** [comment]
Thank you! Update will publish next week with the 21.0.0.3 release

**Comment by kgibm** [comment]
@dmuelle Thanks David. This is my first time submitting a doc PR, so is everything done? I notice there's another step in the README that says to open another PR to vNext?

> After you verify the doc, post a link to it on one of the staging sites in the Git issue and change the issue status to Ready to publish. Open a PR from staging to vNext and Request a review of the PR from David Mueller (dmuelle) or one of the doc maintainers. After the PR is approved and merged to vNext, the changes publish with the next scheduled release.

**Comment by dmuelle** [comment]
Yes- The final step is to open a PR from staging to vNext, which I've just done in #3803. In practice, that final step is usually handled by the docs team, though more out of routine than any particular requirement. I just sent that PR for one last peer review check and I'll merge it in. But unless you see anything unusual in the PR, I think we're done here :)

**Comment by kgibm** [comment]
@dmuelle Great. That's it. Thanks!

**Pull request merged**
