### PR TITLE
Fixes 'shared.config.dir' description

### PR DESCRIPTION
**Pull request by scottkurz**
The description of:
> `shared.config.dir` - the directory that contains the server config....

seems too similar to:
> `server.config.dir` - the directory that server config is stored in.

Went back to [this](https://www.ibm.com/support/knowledgecenter/en/SS7K4U_liberty/com.ibm.websphere.wlp.zseries.doc/ae/rwlp_dirs.html) article, for this (IMHO) better phrasing.

### CODE REVIEW

**Comment by scottkurz** [comment]
Not sure if this project prefers an issue or just a PR is OK...I'll pick a reviewer though.

**Comment by lauracowen** [comment]
﻿A PR is fine, esp for a small change like this. But can you change it to target the `develop` branch, please? Thx

**Comment by Charlotte-Holt** [comment]
@scottkurz The change looks good to me, but like @lauracowen said, this needs to target the `develop` branch before we merge to `master`.  Thanks!

**Comment by scottkurz** [comment]
Done.

**Pull request merged**
