### PR TITLE
Add .html to the guides links

### PR DESCRIPTION
**Pull request by anton-balaniuc**
https://openliberty.io/docs/ref/general/#microprofile.html has a few links to other guides, for example:

https://openliberty.io/guides/rest-intro however this links gives 404 because it doesn't have ".html".
The correct addess is https://openliberty.io/guides/rest-intro.html.

All other pages have .html:
```
grep -oe ':\/guides\/.*\[' *.adoc                                                                                                                                                                                                                                                                                                                  ref/general|docs
cloud_native_microservices.adoc::/guides/microprofile-config-intro.html[
cloud_native_microservices.adoc::/guides/retry-timeout.html[
cloud_native_microservices.adoc::/guides/?search=microprofile&key=tag[
health-check-microservices.adoc::/guides/microprofile-health[Adding health reports to microservices] and link:/guides/kubernetes-microprofile-health[
metrics-catalog.adoc::/guides/microprofile-metrics.html[
==========Only microprofile has links without extension====================
microprofile.adoc::/guides/rest-intro[
microprofile.adoc::/guides/microprofile-rest-client[
microprofile.adoc::/guides/microprofile-openapi[
microprofile.adoc::/guides/microprofile-fallback[
microprofile.adoc::/guides/retry-timeout[
microprofile.adoc::/guides/circuit-breaker[
microprofile.adoc::/guides/bulkhead[
microprofile.adoc::/guides/microprofile-jwt[
microprofile.adoc::/guides/microprofile-config[
microprofile.adoc::/guides/microprofile-config-intro[
microprofile.adoc::/guides/microprofile-health[
microprofile.adoc::/guides/kubernetes-microprofile-health[
microprofile.adoc::/guides/microprofile-metrics[
microprofile.adoc::/guides/microprofile-opentracing[
=========================================================================
microservice_observability_metrics.adoc::/guides/microprofile-metrics.html[
rest_clients.adoc::/guides/microprofile-rest-client.html[
rest_microservices.adoc::/guides/microprofile-openapi.html[
sync_async_rest_clients.adoc::/guides/microprofile-rest-client.html[
```

### CODE REVIEW

**Comment by anton-balaniuc** [comment]
@lauracowen Thanks a lot for reviewing my change, I have added `signed-off-by` to my commit.

**Comment by Charlotte-Holt** [comment]
Hi, @anton-balaniuc. Thanks for adding the sign-off to your commit. One last thing, could you re-target this PR to the `develop` branch, rather than `master`? We merge everything to `develop` when it's ready to publish, before merging to `master` for publishing. 

Apologies again for the additional request. I'll be adding this bit about merging first to the `develop` branch to a contributing instructions doc in the near future.

**Comment by Charlotte-Holt** [comment]
Contributions here are covered by CLA. Merging this PR.

**Comment by anton-balaniuc** [comment]
@Charlotte-Holt  you are welcome, is there a similar process for updating the guides. 
For example https://github.com/OpenLiberty/guide-getting-started/pull/113 and https://github.com/OpenLiberty/sample-getting-started/pull/39

**Comment by lauracowen** [comment]
@anton-balaniuc Now you've done the CLA, you're covered under that for making any contributions to the Open Liberty project. So I'll point the relevant people at your guide PRs.

**Pull request merged**
