### PR TITLE
created branch called latest a copy of v22.0.0.1 to test - Change latest doc version in URL from numerical to 'latest' #2363

### PR DESCRIPTION
**Pull request by Sreejith-Websphere**

### CODE REVIEW

**Review by steven1046 — APPROVED** [review]

**Review by dmuelle — COMMENTED** [review]
the conflicts are coming from the changes in the reference nav.adoc. Since draft always has content that might not be ready for staging, the nav files are not in sync across draft/stage/ vNext. To make changes to the nav files on draft, commit from the `draft-nav` branch. Then to go to staging, the changes will have to be recreated on the `staging-nav` branch.

**Review by dmuelle — CHANGES_REQUESTED** [review]
the conflicts are coming from the changes in the reference nav.adoc. Since draft always has content that might not be ready for staging, the nav files are not in sync across draft/stage/ vNext. To make changes to the nav files on draft, commit from the `draft-nav` branch. Then to go to staging, the changes will have to be recreated on the `staging-nav` branch.

**Comment by dmuelle** [comment]
also- since draft was merged into this branch in [a72a9b1](https://github.com/OpenLiberty/docs/pull/5132/commits/a72a9b129e92bd682f9db1679562ab86de12b4e5), it wont be able to commit to staging. Recommend recreating the changes from a new vNext-based branch- the conflicts will likely disappear unless you intended to edit the nav.adoc file

**Comment by Sreejith-Websphere** [comment]
@dmuelle actually this branch is created just to test latest version, but now using Antora 3.0 updating yml file is enough to convert latest version to symbolic version. so since this latest branch is merged with draft  can i copy nav.adoc content from VNext branch and add to this latest branch to resolve conflicts right?

**Comment by dmuelle** [comment]
Looking closer at the changes- we don't want the nav file on draft to say "TOC for the docs on the published OL website" because the draft nav has topics that aren't on the published site. I think the original comment is helpful to determine which version of the TOC you are editing. We want a different comment on draft than on staging/vNext

**Comment by Sreejith-Websphere** [comment]
please look at the resolved conflict

**Review by dmuelle — APPROVED** [review]
LGTM thanks!

**Comment by dmuelle** [comment]
@Sreejith-Websphere is this PR still needed? I doesn't appear to contain any actual content changes

**Comment by Sreejith-Websphere** [comment]
No it just created for testing that is why I didn't merged

**Pull request closed without merging**
